version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '27081:80'
    container_name: wxcloud_junce
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=junce
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Zw47XX0()
      - MYSQL_ADDRESS=10.2.106.5:3306 
      - LOG_LEVEL=info
networks:
  default:
    external:
      name: wxcb0
